[package]
name = "actix_weather"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
env_logger = "0.11.3"
log = "0.4.22"
mime = "0.3.17"
rand = "0.8.5"
serde =  { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
